version: '3.7'

services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules  # Ensures node_modules aren't overwritten by the host
    ports:
      - "5173:5173"  # Expose Vite dev server port
    environment:
      - CHOKIDAR_USEPOLLING=true  # Force file watching through polling
    command: npm run dev -- --host  # Start Vite dev server with host binding
